version: '3.1'
services:
  app:
    build:
      context: .
      # args:
      #   - GITHUB_TOKEN=${GITHUB_TOKEN}
    volumes:
      - .:/apps
    environment:
      - TZ=Asia/Tokyo
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_REGION=ap-northeast-1
    dns:
      - 8.8.8.8
      - 172.20.0.11
